CiklumTestApp/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CiklumTestApp.Models
{
    public class Photo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhotoPath { get; set; }
        public string ThumbnailsPath { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime UploadDate { get; set; }
    }
}

CiklumTestApp/Controllers/PhotoController.cs
using CiklumTestApp.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CiklumTestApp.Controllers
{
    public class PhotoController : Controller
    {
        GalleryContext _context = new GalleryContext();
        int _pageSize = 9;

        public ActionResult Index(int page = 1)
        {
            GalleryViewModel gallery = new GalleryViewModel();
            gallery.Photos = _context.Photos.OrderByDescending(i => i.UploadDate).Skip((page - 1) * _pageSize).Take(_pageSize).ToList();
            gallery.Pagination = new Pagination()
            {
                CurrentPage = page,
                PageSize = _pageSize,
                TotalPages = (int)Math.Ceiling((decimal)_context.Photos.Count() / _pageSize),
                TotalItems = _context.Photos.Count()
            };

            return View(gallery);
        }

        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                Photo photo = _context.Photos.FirstOrDefault(i => i.Id == id);
                if (photo == null)
                    return HttpNotFound();
                return View(photo);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Upload(string name, HttpPostedFileBase uploadImage)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(name))
                {
                    ViewBag.NameError = "Enter name";
                    return View();
                }
                if (uploadImage == null)
                {
                    ViewBag.PhotoError = "Choose photo";
                    return View();
                }
                string filename = uploadImage.FileName;
                string photoPath = Path.Combine(Server.MapPath("~/Uploads"), filename);
                string thumbnailPath = Path.Combine(Server.MapPath("~/Uploads/Thumbnails"), filename);
                string shortPhotoPath = string.Format("/Uploads/{0}", filename);
                string shortThumbPath = string.Format("/Uploads/Thumbnails/{0}", filename);

                var file = _context.Photos.FirstOrDefault(i => i.PhotoPath == shortPhotoPath);
                if (file != null)
                {
                    ViewBag.Message = "File already exists";
                    return View();
                }
                uploadImage.SaveAs(photoPath);
                Image newImage = new Bitmap(Image.FromStream(uploadImage.InputStream), new Size(300, 200));
                newImage.Save(thumbnailPath);
                _context.Photos.Add(new Photo()
                {
                    Name = name,
                    PhotoPath = shortPhotoPath,
                    ThumbnailsPath = shortThumbPath,
                    UploadDate = DateTime.Now
                });
                _context.SaveChanges();
                ViewBag.Message = "Success";
                return View();
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
    }
}

CiklumTestApp/Views/Photo/Details.cshtml
@model CiklumTestApp.Models.Photo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h3>
        @Html.DisplayFor(model => model.Name)
        <small>
            @Html.DisplayFor(model => model.UploadDate)
        </small>
    </h3>
</div>
<p>
    @Html.ActionLink("Back to Main", "Index")
</p>

<div>
    @if (Model != null)
    {
        <img class="img-thumbnail img-responsive" src="@Model.PhotoPath" />
    }
    else
    {<h1>Photo not found</h1>  }
</div>

CiklumTestApp/Views/Photo/Index.cshtml
@model CiklumTestApp.Models.GalleryViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="form-horizontal">
    <div class="page-header">
        <h3>All photos</h3>
    </div>
    <div class="row">
        @foreach (var i in Model.Photos)
        {
            <div class="col-xs-12 col-md-4 col-lg-4" style="margin-bottom: 10px;">
                <a href="@Url.Action("Details", "Photo", new { id = i.Id })" class="thumbnail">
                    <img src="@i.ThumbnailsPath" />
                </a>
            </div>

        }
    </div>
    @if (Model.Pagination.TotalPages > 1)
    {
        <nav>
            <ul class="pagination pagination-sm">
                @for (int i = 1; i <= Model.Pagination.TotalPages; i++)
                {
                    <li class=@(i == Model.Pagination.CurrentPage ? "active" : "")>
                        @Html.ActionLink(i.ToString(), "Index", "Photo", new { page = i }, null)
                    </li>
                }
            </ul>
        </nav>
        <hr />
    }
</div>


CiklumTestApp/Views/Photo/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-header">
    <h3>Upload photo</h3>
</div>
@if (ViewBag.Message != null)
{
    <div class="alert  alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @ViewBag.Message
    </div>
}
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Upload", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                @Html.Label("Name")
                <input type="text" name="name" class="form-control" /><span class="text-danger">@ViewBag.NameError</span>
            </div>
            <div class="form-group">
                @Html.Label("Photo")
                <input type="file" name="uploadImage" class="form-control" accept=".png, .jpg" /><span class="text-danger">@ViewBag.PhotoError</span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Save" />
            </div>
        }
    </div>
</div>